<?xml version="1.0" ?>
<sdf version="1.9" xmlns:xacro="http://ros.org/wiki/xacro">
    <model name="diffarm" canonical_link="chassis">

        <xacro:property name="wheel_radius" value="0.4"/>
        <xacro:property name="wheel_length" value="0.2"/>
        <xacro:property name="chassis_x" value="2.0"/>
        <xacro:property name="chassis_y" value="1.0"/>
        <xacro:property name="chassis_z" value="0.5"/>
        <xacro:property name="caster_radius" value="${wheel_radius/2}"/>

        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>${chassis_y+wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>1</odom_publish_frequency>
            <topic>cmd_vel</topic>
        </plugin>

        <xacro:include filename="diffarm/chassis.sdf.xacro"/>
        <xacro:include filename="diffarm/wheel.sdf.xacro"/>
        <xacro:include filename="diffarm/caster_wheel.sdf.xacro"/>
        <xacro:include filename="arm.sdf.xacro"/>

    </model>
</sdf>
