<?xml version="1.0" ?>
<sdf version="1.9" xmlns:xacro="http://ros.org/wiki/xacro">
    <frame name="caster_frame" attached_to='chassis'>
        <pose>${chassis_y-caster_radius} 0 -${caster_radius} 0 0 0</pose>
    </frame>

    <link name='caster'>
        <pose relative_to='caster_frame'/>
        <inertial>
            <mass>1</mass>
            <inertia>
                <ixx>0.016</ixx>
                <ixy>0</ixy>
                <ixz>0</ixz>
                <iyy>0.016</iyy>
                <iyz>0</iyz>
                <izz>0.016</izz>
            </inertia>
        </inertial>
        <visual name='visual'>
            <geometry>
                <sphere>
                    <radius>${caster_radius}</radius>
                </sphere>
            </geometry>
            <material>
                <ambient>0.0 1 0.0 1</ambient>
                <diffuse>0.0 1 0.0 1</diffuse>
                <specular>0.0 1 0.0 1</specular>
            </material>
        </visual>
        <collision name='collision'>
            <geometry>
                <sphere>
                    <radius>${caster_radius}</radius>
                </sphere>
            </geometry>
        </collision>
    </link>

    <joint name='caster_wheel' type='ball'>
        <parent>chassis</parent>
        <child>caster</child>
    </joint>
</sdf>
